### ISSUE TITLE
API error when try to generate video

### ISSUE THREAD

**Issue by sintanial** [bhuman-ai/public_api#8]
When i send request like this
```typescript
const body = `{"names":[["Rodrigo"],["https://example.com/yN4HZW9"]],"variables":["first name","onepager"],"campaign_id":"0b6a3ccb"}`
const generateResponse = await fetch('https://studio.bhuman.ai/api/ai_studio/pipeline/campaign', {
    method: 'POST',
    headers,
    body: body,
});
```

I receive HTTP error 422 with text like this 'Failed to deserialize the JSON body into the target type: UUID parsing failed: invalid length: expected length 32 for simple format, found 8 at line 1 column 120'

**Comment by djkskqyr3** [comment]
Campaign id should be UUID type.

https://github.com/bhuman-ai/public_api?tab=readme-ov-file#understanding-urls

`names":[["Rodrigo"],["https://example.com/yN4HZW9"]]`

Also, we are not recommended to use http urls in `names` field.
We recommended to use normal words for variables.

**Comment by sintanial** [comment]
Thx, my mistake ))
